site_name: Mastering Algorithms and Data Structures
docs_dir: "doc"
repo_url: https://github.com/RomeroGabriel/mastering-data-structures
repo_name: RomeroGabriel/mastering-data-structures

nav:
  - Home:
    - index.md
  # Add material parts
  - Big O: bigO.md
  - Search:
    - Binary Search: search/binary.md
  - Sort:
    - Bubble Sort: sort/bubble_sort.md

theme:
  name: material
  language: en
#   logo: images/
#   favicon: images/
  palette:
      scheme: slate
      primary: blue
      accent: white
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.instant
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
